// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnhKb3JwkmDXXmvAGNHhGylI6miGm6zSE',
    appId: '1:655431803823:web:79f333bf12ef03b4dcc55a',
    messagingSenderId: '655431803823',
    projectId: 'krch-chat-app',
    authDomain: 'krch-chat-app.firebaseapp.com',
    storageBucket: 'krch-chat-app.appspot.com',
    measurementId: 'G-2CTRFF919K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbWIQdAJVA6ROfNVtl76JbNgbnUArUeto',
    appId: '1:655431803823:android:d4339166c5e551e1dcc55a',
    messagingSenderId: '655431803823',
    projectId: 'krch-chat-app',
    storageBucket: 'krch-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5-oSDMP4w-RJCEW20emQhIIxRinw5EYs',
    appId: '1:655431803823:ios:9a44bb0ba174a608dcc55a',
    messagingSenderId: '655431803823',
    projectId: 'krch-chat-app',
    storageBucket: 'krch-chat-app.appspot.com',
    iosBundleId: 'com.example.krchChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5-oSDMP4w-RJCEW20emQhIIxRinw5EYs',
    appId: '1:655431803823:ios:9a44bb0ba174a608dcc55a',
    messagingSenderId: '655431803823',
    projectId: 'krch-chat-app',
    storageBucket: 'krch-chat-app.appspot.com',
    iosBundleId: 'com.example.krchChatApp',
  );
}
